### ISSUE TITLE
not able to retrieve data and path

### ISSUE THREAD

**Issue by komal3** [wdi-atx-10/class#11]
$.ajax({
       url: domain + '/animals',
      method: 'GET',

    
     }).done(function(response){
      
      console.log('Got all the animals ', response);
addPetLocal(response)
    }).fail(function(error){
       console.error('Error: ', error);
   });

   };
   function addPetLocal(response){
     for(var i=0; i<8; i++){

     var image = response[i].imageUrl;
     var name = response[i].name;
     var shelterId = response[i]._id;

   $('.thumbnail').prepend([
     '<div class="col-sm-3 crop">',
     '<a href = "/details.html?' +shelterId+ '">',
     '<img src="'+(image || 'https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg')+'" class="img-responsive browseImg"/>',
     '<p>'+ name +'</p>',
     '<p>'+ shelterId +'</p>',
       '</a>',
       '</div>'
    ].join(''));
  };
 };

**Comment by dirkdunn** [comment]
Hi Komal, I am unable to read this because of the way it is formatted, you can format it correctly by pasting in the code first, and then highlighting all of it, and then clicking the "<>" button above the form.

**Comment by dirkdunn** [comment]
Also, if I could get a brief description of the issue to get further context that would be helpful.
