### ISSUE TITLE
Git Merge Master Conflicts 

### ISSUE THREAD

**Issue by Jorge-Cano** [wdi-atx-10/class#3]
----Taken From my command line----

$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 4 and 7 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:

	deleted:    backend/models/schedules.js
	new file:   frontend/js/test_map.js
	new file:   frontend/styles/test_map.css
	new file:   frontend/test_map.html

Unmerged paths:
  (use "git add <file>..." to mark resolution)

--- I've attempted to change those files and continue to commit, but more error occur.

**Comment by dirkdunn** [comment]
Did you 

`git add .
`
and then

`git commit -m "commit message"
`
?

**Comment by Jorge-Cano** [comment]
Yes, there's a lot more that was written in the command line prior, but essentially what I've been doing incorrectly is just working in master OR my team made some changes yesterday without merging locally prior to Pushing & it's caused master to have diverged...

Kinda tough to explain and be 100% sure what is happening
After further research I believe a few commands that can get me back to a correct setting would be:

http://stackoverflow.com/questions/2452226/master-branch-and-origin-master-have-diverged-how-to-undiverge-branches

Merge
Use the git merge command:
$ git merge origin/master

OR

Rebase
Use the git rebase command:
$ git rebase origin/master
