### ISSUE TITLE
looping issue

### ISSUE THREAD

**Issue by patientplatypus** [wdi-atx-10/class#5]
im trying to loop over a string array and im pulling each of the letters instead of the string

**Comment by dirkdunn** [comment]
ok, so pull the string

**Comment by dirkdunn** [comment]
Do you have any code to share on here so that I can see more into the issue? Or have you figured this out?

**Comment by mdang** [comment]
This is a sign that you are looping through only one element of the array as opposed to the array itself. Make sure that the argument being passed in is an array and not just a string with `console.log()`

**Comment by patientplatypus** [comment]
I got it! Thanks for the help :D
